### ISSUE TITLE
Sockets MySQL connection doesn't work

### ISSUE THREAD

**Issue by paskal** [zabbix/zabbix-docker#1074]
I'm looking at file https://github.com/zabbix/zabbix-docker/blob/0fa87156974e799e04bf99e5300bad6830d754ab/Dockerfiles/server-mysql/alpine/docker-entrypoint.sh, and it looks to me that `update_config_var $ZBX_CONFIG "DBSocket" "${DB_SERVER_SOCKET}"` and whole `update_zbx_config` function is not called as it's blocked by function `check_db_connect_mysql ` as it doesn't support socket and relies on the ability to log into the database using TCP port. That results in a crash loop on startup (with `DEBUG_MODE` enabled):

```
zabbix-server  | + '[' '!' '' ']'
zabbix-server  | + echo '**** MySQL server is not available. Waiting 5 seconds...'
zabbix-server  | **** MySQL server is not available. Waiting 5 seconds...
zabbix-server  | + sleep 5
```

The fix would be making `check_db_connect_mysql` aware of the `DB_SERVER_SOCKET` variable.

**Comment by dotneft** [comment]
Fixed!

**Comment by paskal** [comment]
@dotneft, thanks a lot! But zabbix-web-mysql doesn't work still. The health check script is working, but the connection is impossible with the following error shown in the web interface

```
Database error
php_network_getaddresses: getaddrinfo for mysql-server failed: Name does not resolve
```

I believe something is missing inside `/etc/zabbix/web/zabbix.conf.php`. Some set of options should be set for socket connection to work, but now nothing is set.

**Comment by paskal** [comment]
I got to the bottom of it: it works, but only with the env variable `DB_SERVER_HOST=localhost`: I propose to add some log message in case `DB_SERVER_SOCKET` is specified but `DB_SERVER_HOST` is not, or even change the default in such case from `mysql-server` to `localhost` so it would work automatically as expected.

**Comment by dotneft** [comment]
Dear Paskal,

What variables did you pass when catch the error? Where did you see such error?

**Comment by paskal** [comment]
Here is the docker-compose config:

```yaml
  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    hostname: zabbix-web
    restart: always
    depends_on:
      - zabbix-server

    # MYSQL_DATABASE, MYSQL_PASSWORD, MYSQL_USER
    env_file: private/environment/mysql.env
    environment:
      - DB_SERVER_HOST=localhost
      - DB_SERVER_SOCKET=/var/run/mysqld/mysqld.sock
      - ZBX_SERVER_HOST=zabbix-server
    expose:
      - "8080"
    volumes:
      # MySQL socket to prevent transferring data through TCP
      - ./private/mysqld:/var/run/mysqld
```

Problem manifests itself if I remove `DB_SERVER_HOST` variable.

**Comment by dotneft** [comment]
Fixed! Please verify.

**Comment by paskal** [comment]
All good, thank you!

**Comment by prajaktapatil60** [comment]
> I got to the bottom of it: it works, but only with the env variable `DB_SERVER_HOST=localhost`: I propose to add some log message in case `DB_SERVER_SOCKET` is specified but `DB_SERVER_HOST` is not, or even change the default in such case from `mysql-server` to `localhost` so it would work automatically as expected.

We are also facing the same issue, we tried setting DB_SERVER_HOST=localhost but we are still getting the error "Database error"
