### ISSUE TITLE
Latest proxy mysql alpine image breaks unencrypted SQL DB connections

### ISSUE THREAD

**Issue by Bunkham** [zabbix/zabbix-docker#1812]
Hi there,

I am using the docker image "zabbix/zabbix-proxy-mysql:alpine-7.0-latest". Upon pulling the latest image approximately 10 hours ago I now have the following error in the logs:

"[Z3001] connection to database 'zabbix_proxy' failed: [2026] TLS/SSL error: self-signed certificate in certificate chain
     1:20251205:140707.820 database is down: reconnecting in 10 seconds"

This problem has happened to 3 proxies I am running and I haven't made any config changes to zabbix or mysql. My DB image hasn't changed and I notice a commit was recently made relating to MariaDB TLS errors so think this may be an unintended side affect.

Thanks

**Comment by ThomasHamilcaro** [comment]
Same issue here, but first time using Zabbix so, i'd think maybe the problem is me.
Comment for have update on this topic.

**Comment by dotneft** [comment]
Known issue, related to https://support.zabbix.com/browse/ZBX-27295. Please wait rebuilding. It is currently in progress.

**Comment by dotneft** [comment]
Fixed!

**Comment by viper2pt0** [comment]
Still happening for me.  Was working again late Friday after pulling a new image, but watchtower updated my container yesterday and now it's not working again.  Using zabbix/zabbix-server-mysql:latest.  Error in the docker logs is same as on Friday: connection to database 'zabbix' failed: [2026] TLS/SSL error: self-signed certificate in certificate chain

**Comment by dotneft** [comment]
did you try to pull?

**Comment by viper2pt0** [comment]
Yes, no new image available after the current one I'm running. Image revision 2043ea4f18f5fedce9b04557cce27fabbd0e4602 (sha256:5cb5ee704c960bb2bd8dc960a3de87d01be8a93a432c56668cb6df45641c7113) was working on Friday night.  Image revision 9890c36327b36d972043356bec75d03fd0ce04d5 (sha256:c40b79db02b09360bf0cc174116abe6bd008a336969838ac7aa1e8c0ce66eff0) was pulled yesterday (and is the most recent that I'm able to pull using the latest tag) and is not working.  I do see sha256-a5e766567e27fdc1a83bc057c577fdce588054a203dab62034d11ccd6893f5ed out there now, but it's not being pulled with :latest.  do I need to specify the tag?
