### ISSUE TITLE
fping on ubuntu:bionic fails to ping

### ISSUE THREAD

**Issue by perithompson** [zabbix/zabbix-docker#476]
When trying to use the icmp ping template I get the error "(null): can't create raw socket (must run as root?) : Address family not supported by protocol"

I looked around for possible reasons but it seems that fping will not work with ipv6 disabled on host.

**Comment by dotneft** [comment]
Fixed! Thank you!

**Comment by perithompson** [comment]
@dotneft  which tag has this fix?  I am still getting fping failed: (null): can't create raw socket (must run as root?) : Address family not supported by protocol after pulling the zabbix-server-pgsql:ubuntu-4.2.4

**Comment by dotneft** [comment]
I tried to use latest one (compiled by myself). I will check zabbix-server-pgsql:ubuntu-4.2.4. Did you use icmpping checks?

**Comment by perithompson** [comment]
yep, the standard `Template Module ICMP Ping: ICMP ping` checks which launches fping, I think it is related to https://github.com/schweikert/fping/issues/118 seems that the bionic apt package library doesn't include the latest patch that would have that fix in, or at least that's what I found when trying to update fping when building my own container from the main image
