### ISSUE TITLE
trunk - web-apache-mysql php parse error

### ISSUE THREAD

**Issue by posuch** [zabbix/zabbix-docker#586]
Seems that something is wrong with /etc/zabbix/web/zabbix.conf.php in web-apache-mysql ( trunk branch )

`[Tue Apr 28 16:51:21.983707 2020] [php7:error] [pid 35] [client someIP:somePORT] PHP Parse error:  syntax error, unexpected '{' in /etc/zabbix/web/zabbix.conf.php on line 20`

I guess:

couple single quotes are missing ?? in $DB['ENCRYPTION']   and $DB['VERIFY_HOST'] ?

![obrázok](https://user-images.githubusercontent.com/52492965/80516770-44222c00-8984-11ea-8790-8073c5cec660.png)

**Comment by dotneft** [comment]
It is correct. Please use the latest image.

**Comment by posuch** [comment]
same thing - do you mean latest ( version 4 )? , my intention is to run version 5 ( trunk ) - till today i was running v5 without problem

![obrázok](https://user-images.githubusercontent.com/52492965/80525756-02987d80-8992-11ea-9d90-46479a6b565d.png)

![obrázok](https://user-images.githubusercontent.com/52492965/80525814-1cd25b80-8992-11ea-9b81-be342a44c34b.png)
 funny thing that centos-trunk starts but with message about min version for php 7.2

![obrázok](https://user-images.githubusercontent.com/52492965/80527038-07f6c780-8994-11ea-8f49-40fb29ecf1a5.png)


![obrázok](https://user-images.githubusercontent.com/52492965/80526879-c1a16880-8993-11ea-8207-60ebfb7256b7.png)

**Comment by dotneft** [comment]
Looks like docker Hub is not updated images yet. Please wait!

**Comment by posuch** [comment]
will try tomorrow morning, thanks

**Comment by dotneft** [comment]
Fixed!

**Comment by daianmartinho** [comment]
Seems that the problem persist with the new images.
Error 500 is present for all combinations of mysql apache/nginx X alpine/centos/ubuntu.
<img width="1255" alt="Captura de Tela 2020-08-26 às 18 44 29" src="https://user-images.githubusercontent.com/8451484/91360567-1089ce00-e7cd-11ea-971f-13fe439a6b70.png">
This is related to what?

**Comment by daianmartinho** [comment]
> Seems that the problem persist with the new images.
> Error 500 is present for all combinations of mysql apache/nginx X alpine/centos/ubuntu.
> <img alt="Captura de Tela 2020-08-26 às 18 44 29" width="1255" src="https://user-images.githubusercontent.com/8451484/91360567-1089ce00-e7cd-11ea-971f-13fe439a6b70.png">
> This is related to what?

[sed](https://github.com/zabbix/zabbix-docker/blob/9dcf47191a82002825fb5ce157a54f055859b9aa/web-nginx-mysql/alpine/docker-entrypoint.sh#L264) failed. I'm trying to understand why.

**Comment by dotneft** [comment]
Please add DEBUG_MODE="true" and show us log from the container.

**Comment by daianmartinho** [comment]
The problem is that if I don't set ZBX_SERVER_PORT, it inherit tcp://10.43.56.188:10051 value, where 10.43.56.188 is the zabbix server service cluster ip, breaking the sed.

**Comment by dotneft** [comment]
Anyway, could you show debug log?
